name: Deploy

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: 165666738053.dkr.ecr.us-east-1.amazonaws.com
          region: us-east-1
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 165666738053.dkr.ecr.us-east-1.amazonaws.com/yashgour:latest
        env:
          AWS_REGION: us-east-1
      - name: Deploy to ECS
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_version: 0.14.7
          tf_actions_config: v1.4.2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
